### ISSUE TITLE
HTTP authentication doesn't work

### ISSUE THREAD

**Issue by danielfranca** [liri-browser/liri-browser#96] opened 2015-09-18 15:52 UTC
When trying to access a site that requires http authentication it doesn't give the option to enter my username/password, it only gives me a "Authentication required" page in response.

**Comment by tim-sueberkrueb** [comment] 2015-09-18 15:54
This is a duplicate of #35

**Comment by danielfranca** [comment] 2015-09-18 15:54
Thanks, quick reply :)

**Closed by tim-sueberkrueb** 2015-09-18 15:54 UTC
Labels: duplicate
