### ISSUE TITLE
Red scrollbar on windows (graphical bug)

### ISSUE THREAD

**Issue by android1111** [liri-browser/liri-browser#131] opened 2015-10-21 17:22 UTC
Every time I search something on windows I get a red scrollbar instead of the normal grey one.
I'm using Windows 10 64bit.

![issue](https://cloud.githubusercontent.com/assets/9696401/10644435/04faa14a-7829-11e5-83e3-f8095ef205fe.png)

**Comment by tim-sueberkrueb** [comment] 2015-10-21 17:36
@android1111 thx for reporting, we're aware of this. This is an duplicate of #39.

**Closed** 2015-10-21 17:37 UTC
Labels: duplicate
