### ISSUE TITLE
Request: Client side decoration

### ISSUE THREAD

**Issue by GabMus** [liri-browser/liri-browser#70] opened 2015-09-13 12:32 UTC
It would be nice if you integrated window controls in the toolbar: it would reduce the size of the window and make the app consistent across different DEs. You should also make a shadow for the window since if it's undecorated some window managers (Mutter for instance) don't draw a shadow behind it.

**Comment by tim-sueberkrueb** [comment] 2015-09-13 13:53
This is a duplicate of #10

**Closed by tim-sueberkrueb** 2015-09-13 13:53 UTC
